Aic 1195 be improve validation tests
aboutbits/spring-boot-testing pull request #2
Opened 2024-09-05 14:36 UTC by SirCotare

2024-09-10 07:02 UTC, mmalfertheiner reviewed
I have a few questions, but in general it looks good.

Could you also add a bit of documentation in the readme?
- How to use it?
- How can I build my own rule?

2024-09-10 07:18 UTC, SirCotare commented on src/main/java/it/aboutbits/springboot/testing/validation/source/BlankValueSource.java
> +    public static void registerType(Class<?> type, Function<Object[], Stream<?>> source) {
I'll add it to the documentation.

This is the tie-in where the application could register additional types.

2024-09-10 07:19 UTC, SirCotare commented on src/main/java/it/aboutbits/springboot/testing/validation/core/BaseValidationAssert.java
> +    );
I'll add it to the documentation.

The tool generally assumes that ANY nested Record should have an @Valid annotation.
This list is a whitelist of classes that are not required to have the annotations. Like all the wrapper types that are not actual sub-structures.

2024-09-10 07:22 UTC, SirCotare commented on src/main/java/it/aboutbits/springboot/testing/validation/source/BiggerThanValueSource.java
> +                RANDOM.ints(minValue, maxValue).limit(5).boxed()
We always test a few values. The one at the edge of validity and some in between.

2024-09-10 07:26 UTC, mmalfertheiner commented on src/main/java/it/aboutbits/springboot/testing/validation/source/BiggerThanValueSource.java
> +        var maxValue = Integer.MAX_VALUE;
Why 5? Wouldn't 1 be enough?

2024-09-10 07:27 UTC, mmalfertheiner commented on src/main/java/it/aboutbits/springboot/testing/validation/source/BiggerThanValueSource.java
> +                RANDOM.ints(minValue, maxValue).limit(5).boxed()
But why 5? Wouldn't 1 be enough?

2024-09-10 07:29 UTC, mmalfertheiner commented on src/main/java/it/aboutbits/springboot/testing/validation/core/BaseValidationAssert.java
> +    );
Can you please document such things, because somebody that did not write the code can not know it.

2024-09-10 09:08 UTC, SirCotare commented on src/main/java/it/aboutbits/springboot/testing/validation/source/BiggerThanValueSource.java
> +                RANDOM.ints(minValue, maxValue).limit(5).boxed()
It seemed to me like a good tradeoff between "too much" and "too little". But you are right: The exact amount of values is an arbitrary number we just have to make up.

2024-09-10 11:33 UTC, mmalfertheiner requested changes
The resulting API is very. I would just propose to clean up the value sources a bit.

2024-09-10 11:33 UTC, mmalfertheiner commented on src/main/java/it/aboutbits/springboot/testing/validation/core/RuleValidator.java
> + * Additionally, we also check of @Valid or @Nullable is present where required according to the rules.
```suggestion
 * Additionally, we also check if @Valid or @Nullable is present where required according to the rules.
```

2024-09-10 11:33 UTC, mmalfertheiner commented on src/main/java/it/aboutbits/springboot/testing/validation/core/RuleValidator.java
> + * @parameterUnderTest A valid parameter we can use as the basis for our mutations. Validation for the unmodified parameter MUST succeed.
```suggestion
 * @parameterUnderTest A valid parameter that we can use as the basis for our mutations. Validation for the unmodified parameter MUST succeed.
```

2024-09-10 11:33 UTC, mmalfertheiner commented on src/main/java/it/aboutbits/springboot/testing/validation/source/BiggerThanValueSource.java
> +                RANDOM.ints(minValue, maxValue).limit(5).boxed()
For this example I would keep minValue, maxValue and 1 random value in between.

2024-09-10 11:33 UTC, mmalfertheiner commented on src/main/java/it/aboutbits/springboot/testing/validation/source/FutureValueSource.java
> +        var currentDateTime = LocalDateTime.now().plusDays(1);
Shouldn't currentDateTime be `LocalDateTime.now()`?

```suggestion
        var currentDateTime = LocalDateTime.now();
```

2024-09-10 11:33 UTC, mmalfertheiner commented on src/main/java/it/aboutbits/springboot/testing/validation/source/FutureValueSource.java
> +        var currentOffsetDateTime = OffsetDateTime.now(ZoneOffset.UTC).plusDays(1);
```suggestion
        var currentOffsetDateTime = OffsetDateTime.now(ZoneOffset.UTC).plusSeconds(1);
```

2024-09-10 11:33 UTC, mmalfertheiner commented on src/main/java/it/aboutbits/springboot/testing/validation/source/FutureValueSource.java
> +                        .limit(4)
Same comment as above

2024-09-10 11:33 UTC, mmalfertheiner commented on src/main/java/it/aboutbits/springboot/testing/validation/source/FutureValueSource.java
> +        var currentDate = LocalDate.now().plusDays(1);
Shouldn't currentDate be `LocalDate.now()`?

```suggestion
        var currentDate = LocalDate.now();
```

2024-09-10 11:33 UTC, mmalfertheiner commented on src/main/java/it/aboutbits/springboot/testing/validation/source/FutureValueSource.java
> +                        .limit(4)
I would propose to simplify the test cases and keep only those two. It doesn't make any difference if we add 2,3 or 4 days.

```suggestion
                Stream.of(largestDate, currentDate.plusDays(1))
```

2024-09-10 11:33 UTC, mmalfertheiner commented on src/main/java/it/aboutbits/springboot/testing/validation/source/PastValueSource.java
> +        var currentDate = LocalDate.now().minusDays(1);
Same comments as in the FutureValueSource apply to this class.

2024-09-11 07:23 UTC, mmalfertheiner approved these changes

2024-09-11 08:31 UTC, merged